"""seed status and edited_at

Revision ID: 03f54ea4a1c9
Revises: 11eba26b723c
Create Date: 2026-02-15 03:36:04.615849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03f54ea4a1c9'
down_revision: Union[str, None] = '11eba26b723c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seeds', sa.Column('edited_at', sa.DateTime(), nullable=True))
    op.add_column('seeds', sa.Column('status', sa.String(length=20), nullable=False))
    op.drop_column('seeds', 'is_archived')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seeds', sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('seeds', 'status')
    op.drop_column('seeds', 'edited_at')
    # ### end Alembic commands ###
