"""add seed_media table

Revision ID: 0ce6b58ebf8f
Revises: 2c535b21072f
Create Date: 2026-02-17 16:23:24.340088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ce6b58ebf8f'
down_revision: Union[str, None] = '2c535b21072f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seed_media',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seed_id', sa.Uuid(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['seed_id'], ['seeds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_seed_media_seed_id', 'seed_media', ['seed_id'], unique=False)
    op.alter_column('seed_views', 'viewed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seed_views', 'viewed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index('idx_seed_media_seed_id', table_name='seed_media')
    op.drop_table('seed_media')
    # ### end Alembic commands ###
