"""add journal memory link

Revision ID: 112211c907ac
Revises: 72ddf4cb85ed
Create Date: 2026-02-17 18:09:20.768568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '112211c907ac'
down_revision: Union[str, None] = '72ddf4cb85ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journals', sa.Column('memory_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'journals', 'memories', ['memory_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'journals', type_='foreignkey')
    op.drop_column('journals', 'memory_id')
    # ### end Alembic commands ###
