"""slightly modified vaults for statistic inclusions

Revision ID: 168fb69932f5
Revises: 7af8086879a0
Create Date: 2026-02-17 03:00:46.099724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '168fb69932f5'
down_revision: Union[str, None] = '7af8086879a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thinking_signals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_seen', sa.Boolean(), nullable=False),
    sa.Column('seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signal_recipient', 'thinking_signals', ['recipient_id'], unique=False)
    op.create_index('idx_signal_vault_id', 'thinking_signals', ['vault_id'], unique=False)
    op.add_column('vaults', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'vaults', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vaults', type_='foreignkey')
    op.drop_column('vaults', 'created_by')
    op.drop_index('idx_signal_vault_id', table_name='thinking_signals')
    op.drop_index('idx_signal_recipient', table_name='thinking_signals')
    op.drop_table('thinking_signals')
    # ### end Alembic commands ###
