"""corrected alembic errors and notification index

Revision ID: 16c1985f77be
Revises: 3fdaeec818ea
Create Date: 2026-02-19 16:24:34.679089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16c1985f77be'
down_revision: Union[str, None] = '3fdaeec818ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_notification_user_id', 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_notification_user_id', table_name='notifications')
    # ### end Alembic commands ###
