"""store hashed otp instead of plain otp

Revision ID: 19ccc1cba684
Revises: 1dfa1524b2c3
Create Date: 2026-02-23 05:32:12.331150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19ccc1cba684'
down_revision: Union[str, None] = '1dfa1524b2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_tokens', sa.Column('otp_hash', sa.String(length=64), nullable=False))
    op.drop_column('password_reset_tokens', 'otp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_tokens', sa.Column('otp', sa.VARCHAR(length=6), autoincrement=False, nullable=False))
    op.drop_column('password_reset_tokens', 'otp_hash')
    # ### end Alembic commands ###
