"""add memory_id to seeds

Revision ID: 1a42aad37169
Revises: 19ccc1cba684
Create Date: 2026-02-23 06:44:19.125738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a42aad37169'
down_revision: Union[str, None] = '19ccc1cba684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seeds', sa.Column('memory_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'seeds', 'memories', ['memory_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seeds', type_='foreignkey')
    op.drop_column('seeds', 'memory_id')
    # ### end Alembic commands ###
