"""add file_path to media tables for hosting media

Revision ID: 1dfa1524b2c3
Revises: 2a71e2a47cb0
Create Date: 2026-02-22 00:29:38.757052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1dfa1524b2c3'
down_revision: Union[str, None] = '2a71e2a47cb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory_media', sa.Column('file_path', sa.String(length=500), nullable=False))
    op.alter_column('memory_media', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('seed_media', sa.Column('file_path', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seed_media', 'file_path')
    op.alter_column('memory_media', 'uploaded_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('memory_media', 'file_path')
    # ### end Alembic commands ###
