"""editting seeds for bloom notification logic

Revision ID: 3fdaeec818ea
Revises: a3b93fefd7e5
Create Date: 2026-02-19 16:08:55.572006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fdaeec818ea'
down_revision: Union[str, None] = 'a3b93fefd7e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'seeds',
        sa.Column(
            'bloom_notified',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('false')
        )
    )
    # ### end Alembic commands ###
    op.alter_column('seeds', 'bloom_notified', server_default=None)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seeds', 'bloom_notified')
    # ### end Alembic commands ###
