"""added extra lookup feature for valut id and user id

Revision ID: ab6658f67175
Revises: ad661d2112f1
Create Date: 2026-02-14 00:02:56.705841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab6658f67175'
down_revision: Union[str, None] = 'ad661d2112f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_user_id', 'vault_memberships', ['user_id'], unique=False)
    op.create_index('idx_vault_id', 'vault_memberships', ['vault_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vault_id', table_name='vault_memberships')
    op.drop_index('idx_user_id', table_name='vault_memberships')
    # ### end Alembic commands ###
