"""add unique constraint to vault_memberships

Revision ID: ad661d2112f1
Revises: 35f979978c3d
Create Date: 2026-02-13 23:52:44.473006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad661d2112f1'
down_revision: Union[str, None] = '35f979978c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_vault_user', 'vault_memberships', ['vault_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_vault_user', 'vault_memberships', type_='unique')
    # ### end Alembic commands ###
