"""added management for media to show with memories

Revision ID: feab1fc9bd1a
Revises: c2f07cccff82
Create Date: 2026-02-14 02:14:36.103710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feab1fc9bd1a'
down_revision: Union[str, None] = 'c2f07cccff82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
